name: Build

on:
  workflow_run:
    workflows: [Lint]
    types:
      - completed

jobs:
  dagger-build-satellite:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # unless you specify the success on the event,
    # this job will also run if the lint workflow was skipped(which is also the case if the condition for the file extension type is false).
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call Dagger Function to build and publish on Github
        uses: dagger/dagger-for-github@v5
        with:
          version: latest
          verb: call
          module: github.com/Mehul-Kumar/harbor-satellite
          args: start --name=satellite --source=. --release=./ci --GITHUB-TOKEN=env:GITHUB_TOKEN --version=$GITHUB_SHA --REPO_OWNER=$GITHUB_USERNAME --REPO_NAME=harbor-satellite --RELEASE_NAME=satellite
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_SHA: ${{ github.sha }}
